// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-m0kgje8BTyZxipdAQ9oOYCGhXti77w',
    appId: '1:145646908405:web:cab88d954fa54a779966bc',
    messagingSenderId: '145646908405',
    projectId: 'weatherapp-36373',
    authDomain: 'weatherapp-36373.firebaseapp.com',
    storageBucket: 'weatherapp-36373.firebasestorage.app',
    measurementId: 'G-WKH239N15L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5emFfELPUQS6WC7wsCTUPgXHNKoD-_TM',
    appId: '1:145646908405:android:c1ffb6525115f9ee9966bc',
    messagingSenderId: '145646908405',
    projectId: 'weatherapp-36373',
    storageBucket: 'weatherapp-36373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8LREOOWJQS9eYa8EwwpevEZO0RvFETtc',
    appId: '1:145646908405:ios:18925ebace7e15ba9966bc',
    messagingSenderId: '145646908405',
    projectId: 'weatherapp-36373',
    storageBucket: 'weatherapp-36373.firebasestorage.app',
    iosBundleId: 'com.example.weathermobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8LREOOWJQS9eYa8EwwpevEZO0RvFETtc',
    appId: '1:145646908405:ios:18925ebace7e15ba9966bc',
    messagingSenderId: '145646908405',
    projectId: 'weatherapp-36373',
    storageBucket: 'weatherapp-36373.firebasestorage.app',
    iosBundleId: 'com.example.weathermobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK-m0kgje8BTyZxipdAQ9oOYCGhXti77w',
    appId: '1:145646908405:web:ac13d48a65e568819966bc',
    messagingSenderId: '145646908405',
    projectId: 'weatherapp-36373',
    authDomain: 'weatherapp-36373.firebaseapp.com',
    storageBucket: 'weatherapp-36373.firebasestorage.app',
    measurementId: 'G-V75FSGQSK5',
  );
}
